namespace Spider.Pipelines.Samples.Web
{
    /// <summary>
    /// Represents a credit offer generated by the complex sample flow.
    /// </summary>
    /// <param name="ApplicationId">The application identifier.</param>
    /// <param name="Status">The offer status.</param>
    /// <param name="ApprovedAmount">The approved credit amount.</param>
    /// <param name="AnnualRate">The annual rate assigned to the offer.</param>
    /// <param name="Channel">The channel or processing lane assigned to the offer.</param>
    public sealed record CreditOffer(
        string ApplicationId,
        string Status,
        decimal ApprovedAmount,
        decimal AnnualRate,
        string Channel);
}
