<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Spider.Pipelines</PackageId>
    <Authors>Elysium Coding</Authors>
    <Company>Elysium Coding</Company>
    <Description>Spider.Pipelines is a lightweight .NET library for composing service execution pipelines with preprocessors, overrides, parallel steps, and postprocessors.</Description>
    <RepositoryUrl>https://github.com/mape1402/spider-pipelines</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/mape1402/spider-pipelines</PackageProjectUrl>
    <PackageIcon>image.png</PackageIcon>
    <PackageReleaseNotes>https://github.com/mape1402/spider-pipelines/releases</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>pipelines pipeline middleware preprocessing postprocessing dependency-injection spider-pipelines elysium</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" Visible="false" PackagePath="" />
    <None Include="../../assets/image.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
